In [1]:
import index_downloader as idx
import asyncio
import pandas as pd
import filings_downloader as fd

In [2]:

# Run the asynchronous download function
# In a Jupyter Notebook, you can use 'await' at the top level.
await idx.download_all_idx_async(1994, 2025, update_mode=True)

# The rest of the code remains the same
df = idx.build_form4_index()
df.head()

🚀 Initializing asynchronous download process...
🚀 Running in fast update mode. Checking only for year 2026...
❌ Failed to fetch directory https://www.sec.gov/Archives/edgar/daily-index/2026/QTR2/: 403, message='Forbidden', url='https://www.sec.gov/Archives/edgar/daily-index/2026/QTR2/'
❌ Failed to fetch directory https://www.sec.gov/Archives/edgar/daily-index/2026/QTR3/: 403, message='Forbidden', url='https://www.sec.gov/Archives/edgar/daily-index/2026/QTR3/'
❌ Failed to fetch directory https://www.sec.gov/Archives/edgar/daily-index/2026/QTR4/: 403, message='Forbidden', url='https://www.sec.gov/Archives/edgar/daily-index/2026/QTR4/'
🔎 Found 33 total files to check.

--- Download Summary ---
✅ Downloaded: 0 new files.
⏩ Skipped: 33 existing files.
------------------------

📁 Found 7684 .idx files to process...
🚀 Starting parallel parsing with 12 processes...

🔍 Processing .idx files: 100%|██████████| 7684/7684 [00:25<00:00, 298.90it/s]

✅ Finished processing. Converting to DataFrame...
📦 Exported Form 4 data: 9155241 rows to all_form4_filings.csv and all_form4_filings.pkl

,Company,Form,CIK,Date,Path
0,AAR CORP,4,1750,20260108,edgar/data/1750/0000001750-26-000004.txt
1,ABM INDUSTRIES INC /DE/,4,771497,20260108,edgar/data/771497/0001225208-26-000522.txt
2,ABM INDUSTRIES INC /DE/,4,771497,20260108,edgar/data/771497/0001225208-26-000523.txt
3,ABM INDUSTRIES INC /DE/,4,771497,20260108,edgar/data/771497/0001225208-26-000524.txt
4,ABM INDUSTRIES INC /DE/,4,771497,20260108,edgar/data/771497/0001225208-26-000525.txt

In [3]:
display(df.describe())
df["Form"].value_counts().reindex(["4", "4/A"]).fillna(0)

,Company,Form,CIK,Date,Path
count,9155241,9155241,9155241,9155241,9155241
unique,286443,2,275113,7049,9119827
top,INTERNATIONAL SPEEDWAY CORP,4,51548,20050104,edgar/data/1022409/0001022409-98-000025.txt
freq,12378,8901401,12378,8802,18

Form
4      8901401
4/A     253840
Name: count, dtype: int64

In [ ]:
cfg = fd.DownloadConfig(
    index_pkl="all_form4_filings.pkl",
    out_dir="./form4_filings",
    min_date=20250101,
    max_workers=10,
    target_rps=9.9,  # keep well under 10 rps cap :contentReference[oaicite:2]{index=2}
    layout="year_cik_accession",
)
\
stats = fd.download_form4_filings(cfg)
stats

📥 Downloading Form 4 / 4A:  21%|██        | 34386/166819 [58:26<3:45:04,  9.81it/s]

: